#include "mm_i8_transparency_map.h"

#include <unordered_set>

namespace bitdeck {

namespace {

const char* const kMmTranslucentI8Textures[] = {
    "objects/gameplay_keep/gEffDust1Tex",
    "objects/gameplay_keep/gEffDust2Tex",
    "objects/gameplay_keep/gEffDust3Tex",
    "objects/gameplay_keep/gEffDust4Tex",
    "objects/gameplay_keep/gEffDust5Tex",
    "objects/gameplay_keep/gEffDust6Tex",
    "objects/gameplay_keep/gEffDust7Tex",
    "objects/gameplay_keep/gEffDust8Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame10Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame1Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame2Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame3Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame4Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame5Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame6Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame7Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame8Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame9Tex",
    "objects/gameplay_keep/gEffFireTex",
    "objects/gameplay_keep/gEffShockwaveTex",
    "objects/gameplay_keep/gEffWaterRippleTex",
    "objects/gameplay_keep/gEffWaterSplash1Tex",
    "objects/gameplay_keep/gEffWaterSplash2Tex",
    "objects/gameplay_keep/gEffWaterSplash3Tex",
    "objects/gameplay_keep/gEffWaterSplash4Tex",
    "objects/gameplay_keep/gEffWaterSplash5Tex",
    "objects/gameplay_keep/gEffWaterSplash6Tex",
    "objects/gameplay_keep/gEffWaterSplash7Tex",
    "objects/gameplay_keep/gEffWaterSplash8Tex",
    "objects/gameplay_keep/gSoaringWarpCsWindCapsuleTex",
    "objects/gameplay_keep/gSongOfTimeClockBottomTex",
    "objects/gameplay_keep/gSpinAttack1Tex",
    "objects/gameplay_keep/gSpinAttack2Tex",
    "objects/gameplay_keep/gSpinAttackCharging1Tex",
    "objects/gameplay_keep/gSpinAttackCharging2Tex",
    "objects/gameplay_keep/gSwordBeam1Tex",
    "objects/gameplay_keep/gSwordBeam2Tex",
    "objects/gameplay_keep/gameplay_keep_Tex_028BB8",
    "objects/gameplay_keep/gameplay_keep_Tex_029150",
    "objects/gameplay_keep/gameplay_keep_Tex_02D430",
    "objects/gameplay_keep/gameplay_keep_Tex_02DC30",
    "objects/gameplay_keep/gameplay_keep_Tex_054E10",
    "objects/gameplay_keep/gameplay_keep_Tex_054F20",
    "objects/gameplay_keep/gameplay_keep_Tex_07D350",
    "objects/gameplay_keep/gameplay_keep_Tex_07EA08",
    "objects/gameplay_keep/gameplay_keep_Tex_08FBE0",
    "objects/object_an1/gAnju1PlateTex",
    "objects/object_an1/gAnju1Steam2Tex",
    "objects/object_big_fwall/gRingOfFireTex",
    "objects/object_bigpo/gBigPoeSoulFaceTex",
    "objects/object_bigslime/gBigslimeShadowTex",
    "objects/object_boss01/gOdolwaEyeTex",
    "objects/object_boss01/gOdolwaSwordTrailTex",
    "objects/object_boss_hakugin/gGohtLightOrbTex",
    "objects/object_box/gBoxLightTex",
    "objects/object_drs/gWeddingDressMannequinFabricSheerTex",
    "objects/object_dy_obj/gGreatFairySpiralBeamGradientTex",
    "objects/object_dy_obj/gGreatFairySpiralBeamPatternTex",
    "objects/object_efc_star_field/object_efc_star_field_Tex_000108",
    "objects/object_efc_tw/gTimewarpTex",
    "objects/object_ending_obj/object_ending_obj_Tex_0005E8",
    "objects/object_ending_obj/object_ending_obj_Tex_000DE8",
    "objects/object_fall/gMoonFireRingFlamesTex",
    "objects/object_fall/gMoonFireRingMaskTex",
    "objects/object_gi_mask06/gGiAllNightMaskFacePattern1Tex",
    "objects/object_gi_mask13/gGiCouplesMaskLeftInscriptionTex",
    "objects/object_gi_nutsmask/gGiDekuMaskHairTex",
    "objects/object_iknv_obj/object_iknv_obj_Tex_006A60",
    "objects/object_iknv_obj/object_iknv_obj_Tex_007360",
    "objects/object_iknv_obj/object_iknv_obj_Tex_008360",
    "objects/object_kamejima/gTurtleWaveTex",
    "objects/object_kamejima/gTurtleWaveUnusedTex",
    "objects/object_kanban/gSignParticleTex",
    "objects/object_knight/object_knight_Tex_018098",
    "objects/object_kumo30/object_kumo30_Tex_000E80",
    "objects/object_kumo30/object_kumo30_Tex_002B58",
    "objects/object_kumo30/object_kumo30_Tex_002F58",
    "objects/object_lastday/object_lastday_Tex_000E10",
    "objects/object_lastday/object_lastday_Tex_001610",
    "objects/object_lastday/object_lastday_Tex_001E10",
    "objects/object_lastday/object_lastday_Tex_002210",
    "objects/object_link_zora/object_link_zora_Tex_012260",
    "objects/object_mask_bakuretu/object_mask_bakuretu_Tex_0007B0",
    "objects/object_mask_bakuretu/object_mask_bakuretu_Tex_000DF0",
    "objects/object_mask_meoto/object_mask_meoto_Tex_0008C8",
    "objects/object_mask_meoto/object_mask_meoto_Tex_0010C8",
    "objects/object_mask_stone/object_mask_stone_Tex_000C40",
    "objects/object_mask_yofukasi/object_mask_yofukasi_Tex_0012A0",
    "objects/object_moonend/object_moonend_Tex_00A530",
    "objects/object_moonend/object_moonend_Tex_00D648",
    "objects/object_moonend/object_moonend_Tex_00EC58",
    "objects/object_moonend/object_moonend_Tex_0111E0",
    "objects/object_moonend/object_moonend_Tex_0121E0",
    "objects/object_msmo/gMoonMaskPatternTex",
    "objects/object_po_composer/gPoeComposerSoulTex",
    "objects/object_smtower/object_smtower_Tex_000778",
    "objects/object_stk2/gSkullKidMajorasMaskCurseOverlayElectricityTex",
    "objects/object_stk2/gSkullKidMajorasMaskCurseOverlayMaskTex",
    "objects/object_stk2/object_stk2_Tex_008B50",
    "objects/object_stk2/object_stk2_Tex_009350",
    "objects/object_stk2/object_stk2_Tex_009750",
    "objects/object_syoten/object_syoten_Tex_000A90",
    "objects/object_syoten/object_syoten_Tex_000E90",
    "objects/object_syoten/object_syoten_Tex_002BA0",
    "objects/object_syoten/object_syoten_Tex_002FA0",
    "objects/object_syoten/object_syoten_Tex_0033A0",
    "objects/object_syoten/object_syoten_Tex_003DA0",
    "objects/object_syoten/object_syoten_Tex_0045A0",
    "objects/object_uch/gAlienEyeBeamMaskTex",
    "objects/object_um/object_um_Tex_004500",
    "objects/object_um/object_um_Tex_004C80",
    "objects/object_warp1/gWarpBossWarpActivationBeamMaskTex",
    "objects/object_warp1/gWarpBossWarpActivationBeamTex",
    "objects/object_warp1/gWarpBossWarpGlowTex",
    "objects/object_warp1/gWarpCrystalTex",
    "objects/object_warp1/gWarpPortalTex",
    "objects/object_water_effect/object_water_effect_Tex_001A60",
    "objects/object_wiz/gWizrobeBigFlameTex",
    "objects/object_wiz/gWizrobeIcePoolTex",
    "objects/object_wiz/gWizrobePlatformLightRaysTex",
    "objects/object_zo/gZoraSplashTex",
    "objects/object_zoraband/object_zoraband_Tex_000330",
    "objects/object_zoraband/object_zoraband_Tex_000730",
    "objects/object_zoraband/object_zoraband_Tex_000B30",
    "overlays/ovl_Arrow_Fire/gFireArrowMaskTex",
    "overlays/ovl_Arrow_Fire/gFireArrowTex",
    "overlays/ovl_Arrow_Ice/gIceArrowMaskTex",
    "overlays/ovl_Arrow_Ice/gIceArrowTex",
    "overlays/ovl_Arrow_Light/gLightArrowMaskTex",
    "overlays/ovl_Arrow_Light/gLightArrowTex",
    "overlays/ovl_En_Clear_Tag/gClearTagFlashEffectTex",
    "overlays/ovl_En_Clear_Tag/gClearTagLightRayEffectTex",
    "overlays/ovl_En_Tru/D_80A890C8",
    "overlays/ovl_En_Tru/D_80A8A188",
    "overlays/ovl_Oceff_Spot/sSunSongEffectTex",
    "overlays/ovl_Oceff_Storm/sSongOfStormsEffectTex",
    "overlays/ovl_Oceff_Wipe/sSongOfTimeEffectTex",
    "overlays/ovl_Oceff_Wipe3/sSariaSongEffectTex",
    "overlays/ovl_Oceff_Wipe7/sSongofHealingEffectTex",
};

} // namespace

bool mmI8TextureIsTranslucent(const std::string& archivePath) {
    static const std::unordered_set<std::string> kSet(
        std::begin(kMmTranslucentI8Textures), std::end(kMmTranslucentI8Textures));
    return kSet.count(archivePath) != 0;
}

} // namespace bitdeck
