#include "oot_i8_transparency_map.h"

#include <unordered_set>

namespace bitdeck {

namespace {

const char* const kOotTranslucentI8Textures[] = {
    "objects/gameplay_field_keep/gFieldSandstorm1Tex",
    "objects/gameplay_keep/gCircleGlowLTex",
    "objects/gameplay_keep/gCircleGlowRTex",
    "objects/gameplay_keep/gCircleGlowSLTex",
    "objects/gameplay_keep/gCircleGlowSRTex",
    "objects/gameplay_keep/gDecorativeFlameTex",
    "objects/gameplay_keep/gDust1Tex",
    "objects/gameplay_keep/gDust2Tex",
    "objects/gameplay_keep/gDust3Tex",
    "objects/gameplay_keep/gDust4Tex",
    "objects/gameplay_keep/gDust5Tex",
    "objects/gameplay_keep/gDust6Tex",
    "objects/gameplay_keep/gDust7Tex",
    "objects/gameplay_keep/gDust8Tex",
    "objects/gameplay_keep/gEffBubble1Tex",
    "objects/gameplay_keep/gEffBubble2Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame10Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame1Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame2Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame3Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame4Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame5Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame6Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame7Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame8Tex",
    "objects/gameplay_keep/gEffEnemyDeathFlame9Tex",
    "objects/gameplay_keep/gEffLightning1Tex",
    "objects/gameplay_keep/gEffLightning2Tex",
    "objects/gameplay_keep/gEffLightning3Tex",
    "objects/gameplay_keep/gEffLightning4Tex",
    "objects/gameplay_keep/gEffLightning5Tex",
    "objects/gameplay_keep/gEffLightning6Tex",
    "objects/gameplay_keep/gEffLightning7Tex",
    "objects/gameplay_keep/gEffLightning8Tex",
    "objects/gameplay_keep/gEffShockwaveTex",
    "objects/gameplay_keep/gEffUnknown13Tex",
    "objects/gameplay_keep/gEffUnknown14Tex",
    "objects/gameplay_keep/gEffUnknown2Tex",
    "objects/gameplay_keep/gEffUnknown3Tex",
    "objects/gameplay_keep/gEffUnknown4Tex",
    "objects/gameplay_keep/gEffUnknown5Tex",
    "objects/gameplay_keep/gEffWaterRippleTex",
    "objects/gameplay_keep/gEffWaterSplash1Tex",
    "objects/gameplay_keep/gEffWaterSplash2Tex",
    "objects/gameplay_keep/gEffWaterSplash3Tex",
    "objects/gameplay_keep/gEffWaterSplash4Tex",
    "objects/gameplay_keep/gEffWaterSplash5Tex",
    "objects/gameplay_keep/gEffWaterSplash6Tex",
    "objects/gameplay_keep/gEffWaterSplash7Tex",
    "objects/gameplay_keep/gEffWaterSplash8Tex",
    "objects/gameplay_keep/gFairyWingTex",
    "objects/gameplay_keep/gHeartShapeTex",
    "objects/gameplay_keep/gUnknownCircle6Tex",
    "objects/gameplay_keep/gUnknownEffBlureTex",
    "objects/object_bv/gBarinadeSparkBall1Tex",
    "objects/object_bv/gBarinadeSparkBall2Tex",
    "objects/object_bv/gBarinadeSparkBall3Tex",
    "objects/object_bv/gBarinadeSparkBall4Tex",
    "objects/object_bv/gBarinadeSparkBall5Tex",
    "objects/object_bv/gBarinadeSparkBall6Tex",
    "objects/object_bv/gBarinadeSparkBall7Tex",
    "objects/object_bv/gBarinadeSparkBall8Tex",
    "objects/object_demo_6k/object_demo_6k_Tex_000000",
    "objects/object_demo_6k/object_demo_6k_Tex_0010D0",
    "objects/object_demo_6k/object_demo_6k_Tex_0025E0",
    "objects/object_dh/object_dh_Tex_0080C0",
    "objects/object_dh/object_dh_Tex_0088C0",
    "objects/object_dy_obj/gGreatFairySpiralBeamGradientTex",
    "objects/object_dy_obj/gGreatFairySpiralBeamPatternTex",
    "objects/object_efc_erupc/object_efc_erupc_Tex_000000",
    "objects/object_efc_erupc/object_efc_erupc_Tex_001A30",
    "objects/object_efc_erupc/object_efc_erupc_Tex_0027F0",
    "objects/object_efc_fire_ball/gCreationFireBallFlameEffectTex",
    "objects/object_efc_fire_ball/gCreationFireBallMaskTex",
    "objects/object_efc_lgt_shower/gEnliveningLightTex",
    "objects/object_efc_star_field/object_efc_star_field_Tex_000108",
    "objects/object_efc_tw/gTimeWarpTex",
    "objects/object_fish/gFishingAquariumGlassTex",
    "objects/object_fish/gFishingDustSplashTex",
    "objects/object_fw/gFlareDancerFirePatternTex",
    "objects/object_fw/gFlareDancerFireTex",
    "objects/object_gi_jewel/gGiGoronRubyScintillationTex",
    "objects/object_gnd_magic/object_gnd_magic_Tex_000000",
    "objects/object_gnd_magic/object_gnd_magic_Tex_000800",
    "objects/object_god_lgt/gGoldenGoddessAuraHeadTex",
    "objects/object_god_lgt/gGoldenGoddessAuraMaskTex",
    "objects/object_gt/gTowerCollapseCsFlameSmokeTex",
    "objects/object_ice_objects/gRedIceBlockTex",
    "objects/object_ice_objects/gRedIceWallTex",
    "objects/object_kanban/object_kanban_Tex_0016B0",
    "objects/object_kingdodongo/object_kingdodongo_Tex_009DE8",
    "objects/object_light_ring/gGoldenGoddessLightRingTex",
    "objects/object_ps/gPoeSellerAngrySoulTex",
    "objects/object_ps/gPoeSellerHappySoulTex",
    "objects/object_ps/gPoeSellerSadSoulTex",
    "objects/object_spot02_objects/gEffSunGraveSpark1Tex",
    "objects/object_spot02_objects/gEffSunGraveSpark2Tex",
    "objects/object_spot02_objects/gEffSunGraveSpark3Tex",
    "objects/object_spot02_objects/gEffSunGraveSpark4Tex",
    "objects/object_spot02_objects/gEffSunGraveSpark5Tex",
    "objects/object_spot02_objects/gEffSunGraveSpark6Tex",
    "objects/object_spot02_objects/gEffSunGraveSpark7Tex",
    "objects/object_spot02_objects/gEffSunGraveSpark8Tex",
    "objects/object_spot02_objects/object_spot02_objects_Tex_000000",
    "objects/object_spot02_objects/object_spot02_objects_Tex_000800",
    "objects/object_spot02_objects/object_spot02_objects_Tex_0096B0",
    "objects/object_spot02_objects/object_spot02_objects_Tex_00A2B0",
    "objects/object_spot02_objects/object_spot02_objects_Tex_00AEB0",
    "objects/object_spot02_objects/object_spot02_objects_Tex_00BAB0",
    "objects/object_spot02_objects/object_spot02_objects_Tex_00C6B0",
    "objects/object_spot02_objects/object_spot02_objects_Tex_00D2B0",
    "objects/object_spot02_objects/object_spot02_objects_Tex_00DEB0",
    "objects/object_spot02_objects/object_spot02_objects_Tex_00EAB0",
    "objects/object_spot02_objects/object_spot02_objects_Tex_00F6B0",
    "objects/object_spot02_objects/object_spot02_objects_Tex_0102B0",
    "objects/object_spot02_objects/object_spot02_objects_Tex_010EB0",
    "objects/object_spot02_objects/object_spot02_objects_Tex_011AB0",
    "objects/object_spot07_object/object_spot07_object_Tex_005130",
    "objects/object_toki_objects/object_toki_objects_Tex_000000",
    "objects/object_triforce_spot/gTriforceColumnSide1Tex",
    "objects/object_triforce_spot/gTriforceColumnSide2Tex",
    "objects/object_tw/gTwinrovaBigFlameTex",
    "objects/object_tw/gTwinrovaCircleTex",
    "objects/object_tw/gTwinrovaEffectTex",
    "objects/object_tw/gTwinrovaIcePoolTex",
    "objects/object_tw/gTwinrovaMagicParticleTex",
    "objects/object_warp1/gWarpCrystalTex",
    "objects/object_warp1/gWarpPortalTex",
    "objects/object_zo/gZoraSplashesTex",
    "overlays/ovl_Arrow_Fire/s1Tex",
    "overlays/ovl_Arrow_Fire/s2Tex",
    "overlays/ovl_Arrow_Ice/s1Tex",
    "overlays/ovl_Arrow_Ice/s2Tex",
    "overlays/ovl_Arrow_Light/s1Tex",
    "overlays/ovl_Arrow_Light/s2Tex",
    "overlays/ovl_Bg_Ganon_Otyuka/sFlashTex",
    "overlays/ovl_Boss_Ganon/gGanondorfLightning10Tex",
    "overlays/ovl_Boss_Ganon/gGanondorfLightning11Tex",
    "overlays/ovl_Boss_Ganon/gGanondorfLightning12Tex",
    "overlays/ovl_Boss_Ganon/gGanondorfLightning1Tex",
    "overlays/ovl_Boss_Ganon/gGanondorfLightning2Tex",
    "overlays/ovl_Boss_Ganon/gGanondorfLightning3Tex",
    "overlays/ovl_Boss_Ganon/gGanondorfLightning4Tex",
    "overlays/ovl_Boss_Ganon/gGanondorfLightning5Tex",
    "overlays/ovl_Boss_Ganon/gGanondorfLightning6Tex",
    "overlays/ovl_Boss_Ganon/gGanondorfLightning7Tex",
    "overlays/ovl_Boss_Ganon/gGanondorfLightning8Tex",
    "overlays/ovl_Boss_Ganon/gGanondorfLightning9Tex",
    "overlays/ovl_Boss_Ganon2/gGanonFireRingTex",
    "overlays/ovl_Boss_Ganon2/gGanonLightOrbTex",
    "overlays/ovl_Boss_Ganon2/gGanonMasterSwordShadowTex",
    "overlays/ovl_Boss_Ganon2/gGanonSwordTrailTex",
    "overlays/ovl_Boss_Ganon2/gGanonTriforceTex",
    "overlays/ovl_Boss_Ganon2/gGanonZeldaMagicTex",
    "overlays/ovl_Magic_Dark/sDiamondTex",
    "overlays/ovl_Magic_Wind/sTex",
    "overlays/ovl_Oceff_Spot/sTex",
    "overlays/ovl_Oceff_Storm/sTex",
    "overlays/ovl_Oceff_Wipe/sTex",
    "overlays/ovl_Oceff_Wipe3/sTex",
    "overlays/ovl_Oceff_Wipe4/sTex",
};

} // namespace

bool ootI8TextureIsTranslucent(const std::string& archivePath) {
    static const std::unordered_set<std::string> kSet(
        std::begin(kOotTranslucentI8Textures), std::end(kOotTranslucentI8Textures));
    return kSet.count(archivePath) != 0;
}

} // namespace bitdeck
